package cl.banchile.smprod.suitability;

/**
 * This class was automatically generated by the data modeler tool.
 */


public class ItemConsulta implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String clasificacionRiesgo;
	private java.lang.String codigoFamilia;
	private java.lang.String codigoProducto;
	private java.lang.String familia;
	private java.lang.String nemo;
	private int nivelFamilia;

	public ItemConsulta() {
		super();
		this.clasificacionRiesgo = null;
		this.nemo = null;
		this.codigoProducto = null;
		this.familia = null;
		this.nivelFamilia = -1;
	}

	public java.lang.String getClasificacionRiesgo() {
		return this.clasificacionRiesgo;
	}

	public void setClasificacionRiesgo(java.lang.String clasificacionRiesgo) {
		this.clasificacionRiesgo = clasificacionRiesgo;
	}

	public java.lang.String getCodigoFamilia() {
		return this.codigoFamilia;
	}

	public void setCodigoFamilia(java.lang.String codigoFamilia) {
		this.codigoFamilia = codigoFamilia;
	}

	public java.lang.String getCodigoProducto() {
		return this.codigoProducto;
	}

	public void setCodigoProducto(java.lang.String codigoProducto) {
		this.codigoProducto = codigoProducto;
	}

	public java.lang.String getFamilia() {
		return this.familia;
	}

	public void setFamilia(java.lang.String familia) {
		this.familia = familia;
	}

	public java.lang.String getNemo() {
		return this.nemo;
	}

	public void setNemo(java.lang.String nemo) {
		this.nemo = nemo;
	}

	public int getNivelFamilia() {
		return this.nivelFamilia;
	}

	public void setNivelFamilia(int nivelFamilia) {
		this.nivelFamilia = nivelFamilia;
	}

	public ItemConsulta(java.lang.String clasificacionRiesgo,
			java.lang.String codigoFamilia, java.lang.String codigoProducto,
			java.lang.String familia, java.lang.String nemo, int nivelFamilia) {
		this.clasificacionRiesgo = clasificacionRiesgo;
		this.codigoFamilia = codigoFamilia;
		this.codigoProducto = codigoProducto;
		this.familia = familia;
		this.nemo = nemo;
		this.nivelFamilia = nivelFamilia;
	}

}