package cl.banchile.smprod.suitability;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Poc implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Poc() {
    }




}